
seml:
  executable: scripts/train-mnist-mlp.py
  name: mnist-mlp-3
  output_dir: seml-configs/mnist-mlp-3/log
  project_root_dir: ../../
  conda_environment: torch-cuda

slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 15
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 4G          # memory
    cpus-per-task: 2  # num cores
    time: 0-05:00     # max time, D-HH:MM

fixed:
  initialization_scale: 9.0
  optimization_steps: 100000
  batch_size: 200
  loss_function: "MSE"
  optimizer: "AdamW"
  lr: 0.001
  download_directory: "om/user/ericjm/Downloads/"

  depth: 3
  width: 200
  activation: "ReLU"

  log_freq: 100
  verbose: False


grid:
  weight_decay:
    type: loguniform
    min: 1e-4
    max: 3e-1
    num: 9

  train_points:
    type: choice
    options:
      - 128
      - 256
      - 512
      - 1024
      - 2048
      - 4096
      - 8192
      - 16384
      - 32768
  
  seed:
    type: choice
    options:
      - 0
      - 1
      - 2

