
seml:
  executable: scripts/train-mnist-mlp.py
  name: mnist-mlp-6
  output_dir: seml-configs/mnist-mlp-6/log
  project_root_dir: ../../
  conda_environment: torch-cuda

slurm:
  experiments_per_job: 1
  max_simultaneous_jobs: 400
  sbatch_options:
    gres: gpu:1       # num GPUs
    mem: 4G          # memory
    cpus-per-task: 2  # num cores
    time: 0-06:00     # max time, D-HH:MM

fixed:
  initialization_scale: 9.0
  train_points: 1000
  optimization_steps: 100000
  batch_size: 200
  loss_function: "MSE"
  optimizer: "AdamW"
  lr: 0.001
  download_directory: "/om/user/ericjm/Downloads/"

  depth: 3
  width: 200
  activation: "ReLU"

  log_freq: 100
  verbose: False

grid:
  weight_decay:
    type: choice
    options:
      - 0.0
      - 1e-4
      - 1e-3
      - 1e-2
      - 1e-1
      - 1.0
  seed:
    type: choice
    options:
      - 0
      - 1
      - 2
      - 3

